### ISSUE TITLE
make monitor of ingoing message log available for SRE

### ISSUE THREAD

**Issue by MartinFHansen** [Energinet-DataHub/ARCHIVED-geh-aggregations#633]
There is a need for knowing if the meassage log for incomming messages is running 24/7. for monitoring this SRE team must be able to see if the log is not working.

**Comment by Tm1807** [comment]
1) Introduction of SRE road and concept of SLI and SLO
2) Formulering af SLI sammen med Titans
3) Etabler måling af SLI så den er tilgængelig for SRE on call




Notes:

As an SRE 

I want to know if incoming message logging is running without issues

So that I can exclude this from any further investigations in case of other IT problems, and 

so that I can conclude that a fix has been effective in case of an outage and 





As a Manager in Datahub

I want a monthly report with the average Service level of the incoming messages logging 

so that I can have an informed discussion about the operational performance of the ingoing messages service
